In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np

In [3]:
# Adding two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)
# Multiplying two arrays
result = arr1 * arr2
print(result)

[5 7 9]
[ 4 10 18]


In [4]:
# Adding two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)
# Multiplying two arrays
result = arr1 * arr2
print(result)

[5 7 9]
[ 4 10 18]


In [11]:
# Reshaping a 1D array to a 2D array
arr = np.array([1, 2, 3, 4, 5, 6,7,8])
reshaped_arr = arr.reshape(4,2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
import numpy as np
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [13]:
arr = np.array([1, 2, 3, 4, 5])
max_value = np.max(arr)
min_value = np.min(arr)
print("Max:", max_value)
print("Min:", min_value)

Max: 5
Min: 1


In [16]:
arr = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 4 5]


In [17]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [18]:
# Creating an array of zeros
zeros_arr = np.zeros((2, 3))
print(zeros_arr)
# Creating an array of ones
ones_arr = np.ones((2, 3))
print(ones_arr)
# Creating an identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# Creating an array of zeros
zeros_arr = np.zeros((2, 3))
print(zeros_arr)
# Creating an array of ones
ones_arr = np.ones((2, 3))
print(ones_arr)
# Creating an identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
std_dev = np.std(arr)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 3.0
Standard Deviation: 1.4142135623730951


In [26]:
import pandas as pd